package com.myspace.cc_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class prospects implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("title")
	private java.lang.String title;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("sur_name")
	private java.lang.String sur_name;
	@org.kie.api.definition.type.Label("sa_id")
	private java.lang.String sa_id;
	@org.kie.api.definition.type.Label("martial_status")
	private java.lang.String martial_status;

	@org.kie.api.definition.type.Label("premiumAmount")
	private java.lang.String premiumAmount;

	@org.kie.api.definition.type.Label("approved")
	private java.lang.Boolean approved;

	@org.kie.api.definition.type.Label(value = "prospectUser")
	private java.lang.String prospectUser;

	public prospects() {
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSur_name() {
		return this.sur_name;
	}

	public void setSur_name(java.lang.String sur_name) {
		this.sur_name = sur_name;
	}

	public java.lang.String getSa_id() {
		return this.sa_id;
	}

	public void setSa_id(java.lang.String sa_id) {
		this.sa_id = sa_id;
	}

	public java.lang.String getMartial_status() {
		return this.martial_status;
	}

	public void setMartial_status(java.lang.String martial_status) {
		this.martial_status = martial_status;
	}

	public java.lang.String getPremiumAmount() {
		return this.premiumAmount;
	}

	public void setPremiumAmount(java.lang.String premiumAmount) {
		this.premiumAmount = premiumAmount;
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public java.lang.String getProspectUser() {
		return this.prospectUser;
	}

	public void setProspectUser(java.lang.String prospectUser) {
		this.prospectUser = prospectUser;
	}

	public prospects(java.lang.String title, java.lang.String name,
			java.lang.String sur_name, java.lang.String sa_id,
			java.lang.String martial_status, java.lang.String premiumAmount,
			java.lang.Boolean approved, java.lang.String prospectUser) {
		this.title = title;
		this.name = name;
		this.sur_name = sur_name;
		this.sa_id = sa_id;
		this.martial_status = martial_status;
		this.premiumAmount = premiumAmount;
		this.approved = approved;
		this.prospectUser = prospectUser;
	}

}