package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class channel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("appAvailable")
	private java.lang.String appAvailable;
	@org.kie.api.definition.type.Label("appUUID")
	private java.lang.String appUUID;
	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;
	@org.kie.api.definition.type.Label("mode")
	private java.util.List<java.lang.String> mode;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("firstName")
	private java.lang.String firstName;

	@org.kie.api.definition.type.Label("userProfile")
	private java.lang.String userProfile;

	@org.kie.api.definition.type.Label("surname")
	private java.lang.String surname;

	@org.kie.api.definition.type.Label("title")
	private java.lang.String title;

	@org.kie.api.definition.type.Label("isCustomer")
	private java.lang.Boolean isCustomer;

	@org.kie.api.definition.type.Label("contactPersonIndex")
	private java.lang.Integer contactPersonIndex;

	@org.kie.api.definition.type.Label("contactTime")
	private java.lang.String contactTime;

	@org.kie.api.definition.type.Label("relationship")
	private java.lang.String relationship;

	@org.kie.api.definition.type.Label(value = "prefferedContactNumber")
	private java.lang.String prefferedContactNumber;

	public channel() {
	}

	public java.lang.String getAppAvailable() {
		return this.appAvailable;
	}

	public void setAppAvailable(java.lang.String appAvailable) {
		this.appAvailable = appAvailable;
	}

	public java.lang.String getAppUUID() {
		return this.appUUID;
	}

	public void setAppUUID(java.lang.String appUUID) {
		this.appUUID = appUUID;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.util.List<java.lang.String> getMode() {
		return this.mode;
	}

	public void setMode(java.util.List<java.lang.String> mode) {
		this.mode = mode;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(java.lang.String userProfile) {
		this.userProfile = userProfile;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.Boolean getIsCustomer() {
		return this.isCustomer;
	}

	public void setIsCustomer(java.lang.Boolean isCustomer) {
		this.isCustomer = isCustomer;
	}

	public java.lang.Integer getContactPersonIndex() {
		return this.contactPersonIndex;
	}

	public void setContactPersonIndex(java.lang.Integer contactPersonIndex) {
		this.contactPersonIndex = contactPersonIndex;
	}

	public java.lang.String getContactTime() {
		return this.contactTime;
	}

	public void setContactTime(java.lang.String contactTime) {
		this.contactTime = contactTime;
	}

	public java.lang.String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(java.lang.String relationship) {
		this.relationship = relationship;
	}

	public java.lang.String getPrefferedContactNumber() {
		return this.prefferedContactNumber;
	}

	public void setPrefferedContactNumber(
			java.lang.String prefferedContactNumber) {
		this.prefferedContactNumber = prefferedContactNumber;
	}

	public channel(java.lang.String appAvailable, java.lang.String appUUID,
			java.lang.String contactNumber,
			java.util.List<java.lang.String> mode, java.lang.String name,
			java.lang.String firstName, java.lang.String userProfile,
			java.lang.String surname, java.lang.String title,
			java.lang.Boolean isCustomer, java.lang.Integer contactPersonIndex,
			java.lang.String contactTime, java.lang.String relationship,
			java.lang.String prefferedContactNumber) {
		this.appAvailable = appAvailable;
		this.appUUID = appUUID;
		this.contactNumber = contactNumber;
		this.mode = mode;
		this.name = name;
		this.firstName = firstName;
		this.userProfile = userProfile;
		this.surname = surname;
		this.title = title;
		this.isCustomer = isCustomer;
		this.contactPersonIndex = contactPersonIndex;
		this.contactTime = contactTime;
		this.relationship = relationship;
		this.prefferedContactNumber = prefferedContactNumber;
	}

}