package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dueDateExpiry implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "assessmentId")
	private java.lang.String assessmentId;
	@org.kie.api.definition.type.Label(value = "processInstanceId")
	private java.lang.String processInstanceId;
	@org.kie.api.definition.type.Label(value = "dueDateExpiryIn")
	private java.lang.String dueDateExpiryIn;
	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.Boolean status;

	public dueDateExpiry() {
	}

	public java.lang.String getAssessmentId() {
		return this.assessmentId;
	}

	public void setAssessmentId(java.lang.String assessmentId) {
		this.assessmentId = assessmentId;
	}

	public java.lang.String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getDueDateExpiryIn() {
		return this.dueDateExpiryIn;
	}

	public void setDueDateExpiryIn(java.lang.String dueDateExpiryIn) {
		this.dueDateExpiryIn = dueDateExpiryIn;
	}

	public java.lang.Boolean getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Boolean status) {
		this.status = status;
	}

	public dueDateExpiry(java.lang.String assessmentId,
			java.lang.String processInstanceId,
			java.lang.String dueDateExpiryIn, java.lang.Boolean status) {
		this.assessmentId = assessmentId;
		this.processInstanceId = processInstanceId;
		this.dueDateExpiryIn = dueDateExpiryIn;
		this.status = status;
	}

}