package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class stolenItemDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("vehicleDriver")
	private java.lang.String vehicleDriver;
	@org.kie.api.definition.type.Label("driverDetails")
	private java.lang.String driverDetails;
	@org.kie.api.definition.type.Label("vehicleMileage")
	private java.lang.String vehicleMileage;
	@org.kie.api.definition.type.Label("vehicleDamageArea")
	private java.lang.String vehicleDamageArea;
	@org.kie.api.definition.type.Label("vehicleLastUser")
	private java.lang.String vehicleLastUser;
	@org.kie.api.definition.type.Label("vehicleRecovered")
	private java.lang.String vehicleRecovered;
	@org.kie.api.definition.type.Label("reported")
	private java.lang.Boolean reported;
	@org.kie.api.definition.type.Label("itemRecoveredAddress")
	private java.lang.String itemRecoveredAddress;

	@org.kie.api.definition.type.Label("policeCaseNumber")
	private java.lang.String policeCaseNumber;

	public stolenItemDetails() {
	}

	public java.lang.String getVehicleDriver() {
		return this.vehicleDriver;
	}

	public void setVehicleDriver(java.lang.String vehicleDriver) {
		this.vehicleDriver = vehicleDriver;
	}

	public java.lang.String getDriverDetails() {
		return this.driverDetails;
	}

	public void setDriverDetails(java.lang.String driverDetails) {
		this.driverDetails = driverDetails;
	}

	public java.lang.String getVehicleMileage() {
		return this.vehicleMileage;
	}

	public void setVehicleMileage(java.lang.String vehicleMileage) {
		this.vehicleMileage = vehicleMileage;
	}

	public java.lang.String getVehicleDamageArea() {
		return this.vehicleDamageArea;
	}

	public void setVehicleDamageArea(java.lang.String vehicleDamageArea) {
		this.vehicleDamageArea = vehicleDamageArea;
	}

	public java.lang.String getVehicleLastUser() {
		return this.vehicleLastUser;
	}

	public void setVehicleLastUser(java.lang.String vehicleLastUser) {
		this.vehicleLastUser = vehicleLastUser;
	}

	public java.lang.String getVehicleRecovered() {
		return this.vehicleRecovered;
	}

	public void setVehicleRecovered(java.lang.String vehicleRecovered) {
		this.vehicleRecovered = vehicleRecovered;
	}

	public java.lang.Boolean getReported() {
		return this.reported;
	}

	public void setReported(java.lang.Boolean reported) {
		this.reported = reported;
	}

	public java.lang.String getItemRecoveredAddress() {
		return this.itemRecoveredAddress;
	}

	public void setItemRecoveredAddress(java.lang.String itemRecoveredAddress) {
		this.itemRecoveredAddress = itemRecoveredAddress;
	}

	public java.lang.String getPoliceCaseNumber() {
		return this.policeCaseNumber;
	}

	public void setPoliceCaseNumber(java.lang.String policeCaseNumber) {
		this.policeCaseNumber = policeCaseNumber;
	}

	public stolenItemDetails(java.lang.String vehicleDriver,
			java.lang.String driverDetails, java.lang.String vehicleMileage,
			java.lang.String vehicleDamageArea,
			java.lang.String vehicleLastUser,
			java.lang.String vehicleRecovered, java.lang.Boolean reported,
			java.lang.String itemRecoveredAddress,
			java.lang.String policeCaseNumber) {
		this.vehicleDriver = vehicleDriver;
		this.driverDetails = driverDetails;
		this.vehicleMileage = vehicleMileage;
		this.vehicleDamageArea = vehicleDamageArea;
		this.vehicleLastUser = vehicleLastUser;
		this.vehicleRecovered = vehicleRecovered;
		this.reported = reported;
		this.itemRecoveredAddress = itemRecoveredAddress;
		this.policeCaseNumber = policeCaseNumber;
	}

}